### ISSUE TITLE
Linked to jpeg8

### ISSUE THREAD

**Issue by dopplershift** [conda-forge/jasper-feedstock#2]
So the jasper packages I've gotten from conda-forge are linked against jpeg8 (at least on osx):
```console
>otool -L libjasper.dylib
libjasper.dylib:
	@rpath/libjasper.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
	@rpath/libjpeg.8.dylib (compatibility version 13.0.0, current version 13.0.0)
```
But conda-forge now has jpeg9. This is currently causing CI failures for pygrib, and failures on my system once I remove the homebrew install of jpeg8.

**Comment by pelson** [comment]
The correct solution would be to start adding some annotation to the recipe for pinning the jpeg version. I'm extremely frustrated with the lack of progress from https://github.com/conda/conda-build/pull/747. Pinging @kalefranz as this is the number one issue with conda-build right now - I'm happy to help with finding a solution, but it needs some guidance from you in order to find a healthy solution for conda-build.

**Comment by ocefpaf** [comment]
> The correct solution would be to start adding some annotation to the recipe for pinning the jpeg version.

Indeed. I am preparing PRs to add that.
